In [9]:
import requests as r
from bs4 import BeautifulSoup as bs
import pandas as pd

h1_text = ""

tableresponse = r.get("https://www.scrapethissite.com/pages/forms/")
with open("TableData.html","w") as file:
    file.write(tableresponse.text)
with open("TableData.html","r") as file:
    sourceCode = file.read()
    soup = bs(sourceCode,"html.parser")
    tableData = soup.find_all("tr")
    tableDataList = []
    if tableresponse == 1:
            h1_text = soup.find("h1").get_text().strip()
    for eachRow in tableData:
        cell = eachRow.find_all(["td","th"])
        singleRow=[]
        for eachCell in cell:
            singleRow.append(eachCell.get_text().strip())
        tableDataList.append(singleRow)
tableDF = pd.DataFrame(tableDataList[1:],columns=tableDataList[0])
print("H1:", h1_text)
tableDF

H1:

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,,0.463,272,272,0
6,Hartford Whalers,1990,31,38,,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,,0.487,273,249,24
10,New Jersey Devils,1990,32,33,,0.4,272,264,8
11,New York Islanders,1990,25,45,,0.312,223,290,-67
12,New York Rangers,1990,36,31,,0.45,297,265,32
13,Philadelphia Flyers,1990,33,37,,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,,0.2,236,354,-118
16,St. Louis Blues,1990,47,22,,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,,0.35,243,315,-72
19,Washington Capitals,1990,37,36,,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
21,Boston Bruins,1991,36,32,,0.45,270,275,-5
22,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
23,Calgary Flames,1991,31,37,,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,,0.45,257,236,21

In [13]:
import pandas as pd
import requests as r
response = r.get("https://fake-json-api.mock.beeceptor.com/users")
# print(response.json())
userResponse = response.json()
userDatadf = pd.DataFrame(userResponse)
userDatadf

,id,name,company,username,email,address,zip,state,country,phone,photo
0,1,Eula Mante,"Rippin, Witting and Langosh",Elmore7,Dewitt64@gmail.com,80206 Hirthe Junction,38867-6576,Nevada,Mauritania,1-711-210-6127 x10477,https://json-server.dev/ai-profiles/8.png
1,2,Marta Faker Attribute Error: person.astName is...,"Pagac, Barrows and Boyer",Polly.Cruickshank,Glenna_DAmore17@yahoo.com,13475 Warren Close,70265-2221,Hawaii,Guyana,208.415.0172,https://json-server.dev/ai-profiles/20.png
2,3,Diego Wyman,"Koelpin, Hickle and Kohler",Anderson.Koss36,Dariana.Boehm@yahoo.com,295 Prosacco Walk,67128-7882,Alaska,Qatar,924-736-1975 x57193,https://json-server.dev/ai-profiles/15.png
3,4,Jennyfer Zemlak,"Waters, Goodwin and Turcotte",Hilton.Streich,Salvador.Cormier@hotmail.com,20654 Kemmer Glens,28786,Oklahoma,Morocco,1-843-612-9010 x001,https://json-server.dev/ai-profiles/82.png
4,5,Van Torphy,Green Group,Gerardo11,Ibrahim28@gmail.com,9685 W Jefferson Street,33601,North Dakota,Armenia,1-248-491-0126,https://json-server.dev/ai-profiles/5.png
5,6,Arianna Mante,Ullrich and Sons,Ozella.Dicki,Ora46@gmail.com,89641 Mayfield Road,51963-6489,New Mexico,Mali,935-880-5874 x161,https://json-server.dev/ai-profiles/56.png
6,7,Holly Bosco,"Runolfsdottir, Dickens and Gerhold",Cecile_Bogisich,Kyle.Skiles53@yahoo.com,925 Oakfield Road,15480-8437,Alabama,Haiti,711-919-1819,https://json-server.dev/ai-profiles/94.png
7,8,Dexter Oberbrunner,Pollich - Lehner,Norris70,Selina71@hotmail.com,730 Manchester Road,59475,Wisconsin,French Guiana,795.534.0580 x6307,https://json-server.dev/ai-profiles/41.png
8,9,Olen Pouros,"MacGyver, Schaden and Senger",Chesley_Schuppe,Herman.Braun62@hotmail.com,49190 Wuckert Landing,88340,Missouri,Tunisia,920-988-3871 x278,https://json-server.dev/ai-profiles/29.png
9,10,Brayan Boyer,VonRueden Inc,Dorris_Gutkowski90,Easton94@hotmail.com,668 Meadow Way,80869,Ohio,Japan,585.540.5871 x4393,https://json-server.dev/ai-profiles/13.png

In [17]:
url = 'https://api.escuelajs.co/api/v1/auth/login'
h = {
    'Content-Type': 'application/json'
}
accesToken = ""
credentials = {"email":"john@mail.com","password":"changeme"}
response = r.post(url,json = credentials,headers=h)
print(response.json())
postresponse = response.json()
accessToken = postresponse['access_token']
print(accessToken)

{'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc3NTQ5MDMyNywiZXhwIjoxNzc3MjE4MzI3fQ.CgeiAMiqF7_0D8ruy-IOxt4BhP5CC_Ke05KAlD-ceVY', 'refresh_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc3NTQ5MDMyNywiZXhwIjoxNzc1NTI2MzI3fQ.DkMbPupT2aRnD_-qCom_hSA4c1CHtI0bCsPSApsWkts'}
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc3NTQ5MDMyNywiZXhwIjoxNzc3MjE4MzI3fQ.CgeiAMiqF7_0D8ruy-IOxt4BhP5CC_Ke05KAlD-ceVY

In [18]:
userProfileUrl = "https://api.escuelajs.co/api/v1/auth/profile"
newheader = {
    "Authorization": f"Bearer {accessToken}"
}
profielResponse = r.get(userProfileUrl,headers=newheader)
print(profielResponse.json())

{'id': 1, 'email': 'john@mail.com', 'password': 'changeme', 'name': 'Jhon', 'role': 'customer', 'avatar': 'https://i.imgur.com/LDOO4Qs.jpg', 'creationAt': '2026-04-06T03:15:21.000Z', 'updatedAt': '2026-04-06T03:15:21.000Z'}